name: build and test
on:
  push:
    branches: [main]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.yaml'

env:
  DOTNET_VERSION: '6.0.401'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Install dependencies
      run: dotnet restore PostgreWebClient/

    - name: Build
      run: dotnet build PostgreWebClient/ --configuration Release --no-restore

    - name: Test
      run: dotnet test PostgreWebClient.UnitTests/ --no-restore --verbosity normal
